version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run:
          command: |
            apt install pdftk
            python3 -m venv venv
            source venv/bin/activate
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            source venv/bin/activate
            python3 -m unittest

